language: node_js
node_js:
- '6'
install:
- npm install
- npm install -g codecov
script:
- npm run test:ci
- codecov
deploy:
  provider: npm
  email: maurizio.cas@gmail.com
  api_key:
    secure: ili/pmaw2LowvqG5ZN35w/0k4SdwowIohb7h1ti5MIjRQmQblWixu3OqQrPkCQfGqxkN3G9XkaUrji4Ld1KFRvpQUDg81IywMaptTNxffSUsORtymFkpwssHzKD1SVgSy+bKaA90x42S4RJH5S20BvtPUECm+lcgrcYGMvC3begeqqvg5l56MsI0tV8o9sT2IgcOw+ODseO+GgOsEF7a1GVuDOZFxmfNeGGsDdqhcBqomA8lg/VATep5UjKmFBwqVfaI5iozCYyi4PN8eRZSrUoOrucS+oEBJQhe8PDNfAno0zKFErYn0cbkzcSe6jlh746YHcIFaD6xPtspd4Bx7P0wsaqpKRivYir6EfSpmtgijSzXCflIW5Opo4lm2YgmprAA3BHVU8PEpEP/IjmBbXzZlfsH4xznWJClis7FFV6fL9jsc9X/AJTGeT9pfRrGKrbOFjEamc4R9FJ4VKshWXUps6OdsqXDXnBWimZlENCgbl/3xa0/CGh+4SEziJagTOUH9SMI0lPDzHBpSqsp8FYo/CvhVpNINuqgwAbUqAPwl/mSrkLHSGTDM3TQqcGIBJ6BWQG1O8RWTECvMMBY1tJiSmHl+ehRDjEXkuZXgVVCF3ONR3/fqRRDeTG+53ElPb3rXxubWD/XD9NOqtVgThR1U+2AIoczFprWagYvX6o=
  on:
    tags: true
